<?php

namespace Bigfoot\Bundle\SeoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MetadataParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetadataParameterRepository extends EntityRepository
{
}
