<?php

namespace Bigfoot\Bundle\SeoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * MetadataParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetadataParameterRepository extends EntityRepository
{
    /**
     * @param $route
     *
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneByRoute($route)
    {
        return $this->createQueryBuilder('e')
            ->select('e, p')
            ->join('e.parameters', 'p')
            ->andWhere('e.route = :route')
            ->setParameter(':route', $route)
            ->useQueryCache(null)
            ->getQuery()
            ->setHint(
                Query::HINT_CUSTOM_OUTPUT_WALKER,
                'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
            )
            ->getOneOrNullResult()
        ;
    }
}
